
debug_show_var("mx", mouse_x)
debug_show_var("my", mouse_y)
debug_show_var("cx", cx)
debug_show_var("cy", cy)
debug_show_var("cw", cw)
debug_show_var("ch", ch)
debug_show_var("umx", umx)
debug_show_var("umy", umy)
debug_show_var("uar", uar)
debug_ini()
