debug_show_var("mi", gridi(mouse_x))
debug_show_var("mj", gridj(mouse_y))
debug_show_var("mx", mouse_x)
debug_show_var("my", mouse_y)
debug_show_var("u", shader.cndl_u)
debug_show_var("v", shader.cndl_v)
debug_ini()
