//debug_show_var("mi", gridi(mouse_x))
//debug_show_var("mj", gridj(mouse_y))
debug_show_var("mx", mouse_x)
debug_show_var("my", mouse_y)
//debug_show_var("u", shader.cndl_u)
//debug_show_var("v", shader.cndl_v)
debug_show_var("cx", cx)
debug_show_var("cy", cy)
debug_show_var("cw", cw)
debug_show_var("ch", ch)
debug_show_var("umx", umx)
debug_show_var("umy", umy)
debug_show_var("uar", uar)
debug_ini()
